In [1]:
import json
import pandas as pd
import numpy as np
import os

In [2]:
first= pd.read_csv('./좌표/first(4326).csv', encoding='UTF8')

In [3]:
first

,Column1,name,address,Latitude,Longitude,상태
0,0,설레임,"제주특별자치도 제주시 애월읍 일주서로 5999-1, 2층",33.447134,126.305766,정좌표
1,82608,해물섬,"제주특별자치도 제주시 애월읍 애월로11길 19, 1층",33.465968,126.320629,정좌표
2,82696,엄지흑돼지,"제주특별자치도 제주시 애월읍 일주서로 6701, 1층",33.471880,126.368180,정좌표
3,82828,비금향,"제주특별자치도 제주시 애월읍 항몽로 133, 1층",33.472562,126.409329,정좌표
4,82842,우미노식탁,"제주특별자치도 제주시 애월읍 금성5길 42-24, 1층",33.447877,126.301242,정좌표
...,...,...,...,...,...,...
995,611801,돈플라이,"제주특별자치도 제주시 연동7길 20, 1층 (연동)",33.488228,126.490608,정좌표
996,611803,노형집밥,"제주특별자치도 제주시 다랑곶1길 9, 1층 (노형동)",33.487583,126.478266,정좌표
997,611813,훈남횟집,"제주특별자치도 제주시 조천읍 함덕13길 7, 1층",33.542080,126.667929,정좌표
998,611973,카페콩03,"제주특별자치도 제주시 고산동산5길 4, 1층 (이도이동)",33.495536,126.533799,정좌표
999,612037,서자매김밥,"제주특별자치도 제주시 원노형로 41-1, 1층 (노형동)",33.485029,126.485236,정좌표

In [4]:
second= pd.read_csv('./좌표/second(4326).csv', encoding='UTF8')

In [5]:
second

,Column1,name,address,Latitude,Longitude,상태
0,612047,외도아나고,"제주특별자치도 제주시 우정로4길 3-5, 1층 (외도일동)",33.491708,126.430183,정좌표
1,612049,정실국수,"제주특별자치도 제주시 아연로 208, 1층 (오라이동)",33.467786,126.510250,정좌표
2,612053,미쁨김밥,"제주특별자치도 제주시 삼봉로 113-2, 1층 (도련일동)",33.511359,126.589403,정좌표
3,612063,제주공간,"제주특별자치도 제주시 노연로 34, 2층 (노형동)",33.485835,126.483810,정좌표
4,612071,시쟈덕,"제주특별자치도 제주시 신광로8길 20, 1층 (연동)",33.487058,126.488189,정좌표
...,...,...,...,...,...,...
995,700093,서사라모이세해장국직영점,"제주특별자치도 제주시 서광로5길 37, 101호 (용담일동)",33.503417,126.514260,정좌표
996,700113,컨츄리,제주특별자치도 제주시 만덕로 23 (건입동),33.514522,126.532226,정좌표
997,700121,금커피별빙수제주일도점,제주특별자치도 제주시 동광로 112 (일도이동),33.506245,126.539474,정좌표
998,700123,저팔계깡통숯불구이,"제주특별자치도 제주시 조천읍 신북로 523, 1층",33.542035,126.666057,정좌표
999,700809,불타는여고24시떡볶이중앙여고점,"제주특별자치도 제주시 구남동5길 14, 1층 (이도이동)",33.489918,126.540294,정좌표

In [6]:
third= pd.read_csv('./좌표/third(4326).csv', encoding='UTF8')

In [7]:
third

,Column1,name,address,Latitude,Longitude,상태
0,700857,서프로와,"제주특별자치도 제주시 테우해안로 132, 지하1층 (이호일동)",33.49776,126.4480,정좌표
1,701426,오캄커피,"제주특별자치도 제주시 광양11길 16, 101호 (이도이동, 희봉빌라)",33.49954,126.5318,정좌표
2,701470,황소곱창,제주특별자치도 제주시 삼무로3길 8 (연동),33.49052,126.4951,정좌표
3,701510,삼아갈비,제주특별자치도 제주시 서광로21길 4-1 (삼도일동),33.50051,126.5222,정좌표
4,701512,최가네옛날손두부집,"제주특별자치도 제주시 사장2길 36, 1층 (연동)",33.48430,126.4921,정좌표
...,...,...,...,...,...,...
995,975256,동동차이나남원점,"제주특별자치도 서귀포시 남원읍 태위로689번길 7, 1층 104호",33.28004,126.7198,정좌표
996,975262,꼬란,"제주특별자치도 서귀포시 동문동로 2, 1층 (서귀동)",33.24962,126.5676,정좌표
997,975396,비비큐올리브치킨제주동홍점,"제주특별자치도 서귀포시 동홍동로26번길 6, 1층 (동홍동)",33.25720,126.5755,정좌표
998,975410,오또도넛,제주특별자치도 서귀포시 중문상로 87 (중문동),33.25593,126.4273,정좌표
999,976096,흑돼지스토리,"제주특별자치도 서귀포시 남원읍 태위로 94-37, 1층",33.27435,126.6590,정좌표

In [8]:
forth= pd.read_csv('./좌표/forth(4326).csv', encoding='UTF8')

In [9]:
forth

,Column1,name,address,Latitude,Longitude,상태
0,976530,네네치킨남원점,"제주특별자치도 서귀포시 남원읍 남원체육관로 342, 상가동 1층 103호 (서귀포남...",33.28054,126.7215,정좌표
1,976602,시카고피자성산점,제주특별자치도 서귀포시 성산읍 일주동로 4232,33.45083,126.9118,정좌표
2,976666,푸른솔,제주특별자치도 서귀포시 남원읍 남한로 11,33.28004,126.7177,정좌표
3,976674,용머리해물정식,제주특별자치도 서귀포시 성산읍 환해장성로 467,33.39875,126.9051,정좌표
4,976694,흑돈플러스,제주특별자치도 서귀포시 대포로 132 (대포동),33.23915,126.4350,정좌표
...,...,...,...,...,...,...
995,1468849,금능포구횟집,제주특별자치도 제주시 한림읍 금능9길 27,33.39031,126.2286,정좌표
996,1468973,할리스커피협재해수욕장점,"제주특별자치도 제주시 한림읍 한림로 330, 1~2층",33.39296,126.2402,정좌표
997,1469137,한치앞도모를바다,"제주특별자치도 제주시 한림읍 협재6길 9, 1층",33.39460,126.2424,정좌표
998,1469363,드링콩,제주특별자치도 제주시 한림읍 한림로 158,33.38574,126.2248,정좌표
999,1469441,샤브왕,제주특별자치도 제주시 한림읍 일주서로 5167,33.39472,126.2570,정좌표

In [10]:
fifth= pd.read_csv('./좌표/fifth(4326).csv', encoding='UTF8')

In [11]:
fifth

,Column1,name,address,Latitude,Longitude,상태
0,1469461,낮에정식밤에갈비,제주특별자치도 제주시 한림읍 한림상로 158,33.41230,126.2689,정좌표
1,1469493,생고기통김치찌개,제주특별자치도 제주시 한림읍 한림로5길 11,33.41353,126.2609,정좌표
2,1469539,다람쥐식탁,"제주특별자치도 제주시 한림읍 명월성로 10, 1층",33.40780,126.2658,정좌표
3,1469751,다시정한림점,"제주특별자치도 제주시 한림읍 한림상로 231, 1층",33.41887,126.2676,정좌표
4,1469763,피자베이한림점,"제주특별자치도 제주시 한림읍 한림중앙로 27, 1층",33.41218,126.2653,정좌표
...,...,...,...,...,...,...
995,1615557,아라주는엄마치킨,제주특별자치도 제주시 산천단동3길 13-2 (아라일동),33.44905,126.5587,정좌표
996,1615576,빨간집연동점,제주특별자치도 제주시 신대로 126 (연동),33.48617,126.4961,정좌표
997,1615588,도갈비,"제주특별자치도 제주시 한라대학로 85 (노형동,프라임빌 102호)",33.47652,126.4793,정좌표
998,1615728,우도동굴도남점,제주특별자치도 제주시 도남로 6 (삼도일동),33.49949,126.5250,정좌표
999,1615730,호야치킨앤닭강정 노형점,제주특별자치도 제주시 정존11길 22 (노형동),33.48576,126.4758,정좌표

In [12]:
sixth= pd.read_csv('./좌표/sixth(4326).csv', encoding='UTF8')

In [13]:
sixth

,Column1,name,address,Latitude,Longitude,상태
0,1615731,난타오천뜨란채점,제주특별자치도 제주시 정존11길 39 (노형동),33.486633,126.474028,정좌표
1,1615738,보해국수,제주특별자치도 제주시 오복4길 6 (이도이동),33.495540,126.536322,정좌표
2,1615741,두남자이야기,제주특별자치도 제주시 삼무로 77 (연동),33.490025,126.495053,정좌표
3,1615853,도리,"제주특별자치도 제주시 도공로 48, 2층 (도두일동)",33.502268,126.466377,정좌표
4,1615897,평산,제주특별자치도 제주시 정든로2길 14 (이도이동),33.497534,126.538639,정좌표
...,...,...,...,...,...,...
995,1718888,씨유제주동문로터리점,"제주특별자치도 제주시 동문로 8, 1층 (일도일동)",33.512900,126.527436,정좌표
996,1718898,가든샐러드,"제주특별자치도 제주시 남광로 123, 1층 (일도이동)",33.498357,126.547400,정좌표
997,1718900,호떡당아라점,"제주특별자치도 제주시 구산로 70, 1층 (아라일동)",33.485053,126.542107,정좌표
998,1718922,루루비건,"제주특별자치도 제주시 연북로 28, 2층 (노형동)",33.481661,126.484421,정좌표
999,1718938,먹쿠슬낭노형점,"제주특별자치도 제주시 정존15길 33, 1층 (노형동)",33.487524,126.476595,정좌표

In [14]:
seventh= pd.read_csv('./좌표/seventh(4326).csv', encoding='UTF8')

In [15]:
seventh

,Column1,name,address,Latitude,Longitude,상태
0,1718954,무우수커피로스터스,제주특별자치도 제주시 조천읍 조천11길 22-2,33.53780,126.6384,정좌표
1,1719034,더벤티제주노형점,"제주특별자치도 제주시 월랑로 5, 1층 (노형동)",33.48669,126.4783,정좌표
2,1719062,베이크,제주특별자치도 제주시 우정로 60 (외도일동),33.48752,126.4307,정좌표
3,1719085,노형로22번가,"제주특별자치도 제주시 노형로 22, 2층 (해안동)",33.46162,126.4505,정좌표
4,1719087,앤티앤스프레즐제주시청점,"제주특별자치도 제주시 중앙로 222, 1층 (이도이동)",33.49975,126.5295,정좌표
...,...,...,...,...,...,...
995,1897322,씨유제주회수사거리점,제주특별자치도 서귀포시 1100로 178 (회수동),33.26304,126.4441,정좌표
996,1897383,남극노인성,제주특별자치도 서귀포시 하신상로 216 (상효동),33.27583,126.6071,정좌표
997,1897395,피자헛서귀포점,"제주특별자치도 서귀포시 일주동로 8590, 1층 (동홍동)",33.25497,126.5704,정좌표
998,1897444,씨유서귀포법환길점,"제주특별자치도 서귀포시 이어도로 1041-1, 1층 (서호동)",33.24504,126.5224,정좌표
999,1897454,벙커 하우스,"제주특별자치도 서귀포시 막숙포로41번길 66, 1층 (법환동)",33.24046,126.5192,정좌표

In [16]:
eighth= pd.read_csv('./좌표/eighth(4326).csv', encoding='UTF8')

In [17]:
eighth

,Column1,name,address,Latitude,Longitude,상태
0,1897688,제주김만복성산점,"제주특별자치도 서귀포시 성산읍 성산등용로17번길 55, 1층 108호",33.46059,126.9299,정좌표
1,1900504,미르봉봉키즈빌,"제주특별자치도 서귀포시 서호중로 86, 2층 (서호동)",33.25396,126.5224,정좌표
2,1900508,빽다방서귀포시청점,"제주특별자치도 서귀포시 중앙로 109, 1층 (서홍동)",33.25447,126.5605,정좌표
3,1900536,랍다:즐겁다,"제주특별자치도 서귀포시 태평로 34-17, 2층 (호근동)",33.24413,126.5260,정좌표
4,1900547,제이아일랜드,"제주특별자치도 서귀포시 성산읍 환해장성로 69, 1층",33.37880,126.8797,정좌표
...,...,...,...,...,...,...
306,1935011,지에스25서귀비석거리점,제주특별자치도 서귀포시 일주동로 8541 (동홍동),33.25453,126.5756,정좌표
307,1935021,하은이네손만두김밥,"제주특별자치도 서귀포시 천제연로 223, 1층 (중문동)",33.25162,126.4285,정좌표
308,1935055,씨유서귀라메르점,"제주특별자치도 서귀포시 중정로5번길 15, 1층 101호 (서귀동)",33.24867,126.5578,정좌표
309,1935064,지에스25서귀파인힐점,"제주특별자치도 서귀포시 홍중로 119-2, 602동 204호 (서홍동, 서강파인힐6차)",33.26365,126.5552,정좌표
310,1935071,한옥마루카페,"제주특별자치도 서귀포시 성산읍 한도로 269-23, 부속동 1층",33.46758,126.9359,정좌표

In [18]:
result1 = pd.concat([first,second,third,forth,fifth,sixth,seventh,eighth])

In [19]:
result1

,Column1,name,address,Latitude,Longitude,상태
0,0,설레임,"제주특별자치도 제주시 애월읍 일주서로 5999-1, 2층",33.447134,126.305766,정좌표
1,82608,해물섬,"제주특별자치도 제주시 애월읍 애월로11길 19, 1층",33.465968,126.320629,정좌표
2,82696,엄지흑돼지,"제주특별자치도 제주시 애월읍 일주서로 6701, 1층",33.471880,126.368180,정좌표
3,82828,비금향,"제주특별자치도 제주시 애월읍 항몽로 133, 1층",33.472562,126.409329,정좌표
4,82842,우미노식탁,"제주특별자치도 제주시 애월읍 금성5길 42-24, 1층",33.447877,126.301242,정좌표
...,...,...,...,...,...,...
306,1935011,지에스25서귀비석거리점,제주특별자치도 서귀포시 일주동로 8541 (동홍동),33.254530,126.575600,정좌표
307,1935021,하은이네손만두김밥,"제주특별자치도 서귀포시 천제연로 223, 1층 (중문동)",33.251620,126.428500,정좌표
308,1935055,씨유서귀라메르점,"제주특별자치도 서귀포시 중정로5번길 15, 1층 101호 (서귀동)",33.248670,126.557800,정좌표
309,1935064,지에스25서귀파인힐점,"제주특별자치도 서귀포시 홍중로 119-2, 602동 204호 (서홍동, 서강파인힐6차)",33.263650,126.555200,정좌표
310,1935071,한옥마루카페,"제주특별자치도 서귀포시 성산읍 한도로 269-23, 부속동 1층",33.467580,126.935900,정좌표

In [20]:
result1 .reset_index(drop=True)

,Column1,name,address,Latitude,Longitude,상태
0,0,설레임,"제주특별자치도 제주시 애월읍 일주서로 5999-1, 2층",33.447134,126.305766,정좌표
1,82608,해물섬,"제주특별자치도 제주시 애월읍 애월로11길 19, 1층",33.465968,126.320629,정좌표
2,82696,엄지흑돼지,"제주특별자치도 제주시 애월읍 일주서로 6701, 1층",33.471880,126.368180,정좌표
3,82828,비금향,"제주특별자치도 제주시 애월읍 항몽로 133, 1층",33.472562,126.409329,정좌표
4,82842,우미노식탁,"제주특별자치도 제주시 애월읍 금성5길 42-24, 1층",33.447877,126.301242,정좌표
...,...,...,...,...,...,...
7306,1935011,지에스25서귀비석거리점,제주특별자치도 서귀포시 일주동로 8541 (동홍동),33.254530,126.575600,정좌표
7307,1935021,하은이네손만두김밥,"제주특별자치도 서귀포시 천제연로 223, 1층 (중문동)",33.251620,126.428500,정좌표
7308,1935055,씨유서귀라메르점,"제주특별자치도 서귀포시 중정로5번길 15, 1층 101호 (서귀동)",33.248670,126.557800,정좌표
7309,1935064,지에스25서귀파인힐점,"제주특별자치도 서귀포시 홍중로 119-2, 602동 204호 (서홍동, 서강파인힐6차)",33.263650,126.555200,정좌표
7310,1935071,한옥마루카페,"제주특별자치도 서귀포시 성산읍 한도로 269-23, 부속동 1층",33.467580,126.935900,정좌표

In [21]:
result1 .to_csv('result1.csv',mode="w",encoding='utf-8')