# 전체 image.json 파일 병합

In [1]:
import pandas as pd

In [5]:
one = pd.read_csv('./navermap_image/image.csv', encoding='utf-8-sig', index_col=0)
two = pd.read_csv('./navermap_image/음식점이미지url_정문_종민_남경.csv', encoding='utf-8-sig', index_col=0)
thr = pd.read_csv('./navermap_image/음식점이미지url_준영_용호_남경.csv', encoding='utf-8-sig', index_col=0)

In [9]:
one.columns = ['rest_name', 'url']
one

         rest_name                                                url
0      피자굽는곰아저씨외도점  https://search.pstatic.net/common/?autoRotate=...
1          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
2          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
3          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
4          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
...            ...                                                ...
23976       한옥마루카페  https://search.pstatic.net/common/?autoRotate=...
23977       한옥마루카페  https://search.pstatic.net/common/?autoRotate=...
23978       한옥마루카페  https://search.pstatic.net/common/?autoRotate=...
23979       한옥마루카페  https://search.pstatic.net/common/?autoRotate=...
23980       한옥마루카페  https://search.pstatic.net/common/?autoRotate=...

[23981 rows x 2 columns]

In [7]:
two

      rest_name                                                url
0      동복리해녀잠수촌  https://search.pstatic.net/common/?autoRotate=...
1      동복리해녀잠수촌  https://search.pstatic.net/common/?autoRotate=...
2      동복리해녀잠수촌  https://search.pstatic.net/common/?autoRotate=...
3      동복리해녀잠수촌  https://search.pstatic.net/common/?autoRotate=...
4      동복리해녀잠수촌  https://search.pstatic.net/common/?autoRotate=...
...         ...                                                ...
64430     이왕돈까스  https://search.pstatic.net/common/?autoRotate=...
64431     이왕돈까스  https://search.pstatic.net/common/?autoRotate=...
64432     이왕돈까스  https://search.pstatic.net/common/?autoRotate=...
64433     이왕돈까스  https://search.pstatic.net/common/?autoRotate=...
64434     이왕돈까스  https://search.pstatic.net/common/?autoRotate=...

[64435 rows x 2 columns]

In [8]:
thr

      rest_name                                                url
0      오조파스타앤피자  https://search.pstatic.net/common/?autoRotate=...
1      오조파스타앤피자  https://search.pstatic.net/common/?autoRotate=...
2      오조파스타앤피자  https://search.pstatic.net/common/?autoRotate=...
3      오조파스타앤피자  https://search.pstatic.net/common/?autoRotate=...
4      오조파스타앤피자  https://search.pstatic.net/common/?autoRotate=...
...         ...                                                ...
72104    제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72105    제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72106    제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72107    제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72108    제주만선갈치  https://search.pstatic.net/common/?autoRotate=...

[72109 rows x 2 columns]

In [10]:
df = pd.concat([one, two, thr])
df

         rest_name                                                url
0      피자굽는곰아저씨외도점  https://search.pstatic.net/common/?autoRotate=...
1          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
2          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
3          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
4          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
...            ...                                                ...
72104       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72105       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72106       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72107       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72108       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...

[160525 rows x 2 columns]

In [13]:
df.drop_duplicates(['rest_name', 'url'])
df

         rest_name                                                url
0      피자굽는곰아저씨외도점  https://search.pstatic.net/common/?autoRotate=...
1          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
2          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
3          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
4          밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
...            ...                                                ...
72104       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72105       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72106       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72107       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
72108       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...

[160525 rows x 2 columns]

In [14]:
df.reset_index(inplace=True)
df

        index    rest_name                                                url
0           0  피자굽는곰아저씨외도점  https://search.pstatic.net/common/?autoRotate=...
1           1      밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
2           2      밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
3           3      밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
4           4      밤수지맨드라미  https://search.pstatic.net/common/?autoRotate=...
...       ...          ...                                                ...
160520  72104       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
160521  72105       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
160522  72106       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
160523  72107       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...
160524  72108       제주만선갈치  https://search.pstatic.net/common/?autoRotate=...

[160525 rows x 3 columns]

In [15]:
del df['index']

In [16]:
df.to_csv('네이버맵_리뷰이미지_url합본.csv', mode='w')